services:
  employee-service:
    build:
#      context: ./employee-service
      dockerfile: Dockerfile
    container_name: employees
    environment:
      - PostgreSQLEntityFramework="Host=employee-db;Port=5432;Database=employeedb;Username=postgres;Password=password;"
      - FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
      - AzureWebJobsStorage=UseDevelopmentStorage=true
    depends_on:
      - postgres
    ports:
      - "3005:80"
    networks:
      - karama-kebab-network

  postgres:
    image: postgres:13
    container_name: employee-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: employeedb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - karama-kebab-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  azurite-data:
  postgres-data:

networks:
  karama-kebab-network:
    driver: bridge
