version: '3.8'

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    command: >
      azurite --loose
      --blobHost 0.0.0.0 --blobPort 10000
      --queueHost 0.0.0.0 --queuePort 10001
      --tableHost 0.0.0.0 --tablePort 10002
      --location /workspace --debug /workspace/debug.log
    volumes:
      - azurite-data:/data
    ports:
      - "10000:10000" # Blob service endpoint
      - "10001:10001" # Queue service endpoint
      - "10002:10002" # Table service endpoint
    networks:
      - karama-kebab-network

  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    volumes:
      - ./keycloak/realm-config/:/opt/keycloak/data/import/
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    # command: ["start-dev", "--import-realm"]
    ports:
      - "8080:8080"
    depends_on:
      - azurite
    networks:
      - karama-kebab-network

  event-service:
    build:
      context: ./event-service
      dockerfile: Dockerfile
    volumes:
      - ./event-service/.env:/app/.env
    depends_on:
      - azurite
      - keycloak
    ports:
      - "3001:3001"
    networks:
      - karama-kebab-network

  availability-service:
    build:
      context: ./availability-service
      dockerfile: Dockerfile
    volumes:
      - ./event-service/.env:/app/.env
    depends_on:
      - azurite
      - keycloak
    ports:
      - "3002:3002"
    networks:
      - karama-kebab-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "3007:3007"
    networks:
      - karama-kebab-network

volumes:
  azurite-data:

networks:
  karama-kebab-network:
    driver: bridge
