apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'duty-service'
        static_configs:
          - targets: ['api-gateway-india-dev.apps.inholland.hcs-lab.nl/duties/metrics']
