#config file 
server:
  host: "localhost"
  port: 8080

cosmos:
  endpoint: "https://<cosmos-db-endpoint>"
  key: "<cosmos-db-key>"
  database: "<database-name>"
  container: "<container-name>"

tableStorage:
  connectionString: "<table-storage-connection-string>"

environment: "tableStorage"  # Or "cosmos"
