# Get All Shifts
GET http://localhost:5001/shifts
Accept: application/json
#Authorization: Bearer <your-jwt-token-if-needed>

### Get Shifts by Employee ID
GET http://localhost:5001/shifts?employeeId=3fa85f64-5717-4562-b3fc-2c963f66afa6
Accept: application/json
#Authorization: Bearer <your-jwt-token-if-needed>


### Get Shift by ID
GET http://localhost:5001/shifts/8b3db2c1-03e0-4736-aa74-c3f7547a8dd3
Accept: application/json
# Authorization: Bearer <your-jwt-token-if-needed>

### Create a new Shift
POST http://localhost:5001/shifts
Content-Type: application/json
Accept: application/json
# Authorization: Bearer <your-jwt-token-if-needed>

{
  "employeeId": "99714276-276e-4029-be84-f0165af4677f",
  "startTime": "2024-11-26T09:00:00",
  "endTime": "2024-11-26T17:00:00",
  "shiftType": "Morning",
  "status": "Scheduled",
  "clockInTime": null,
  "clockOutTime": null,
  "shiftHours": 8.0
}

### Update a Shift by ID
PUT http://localhost:5001/shifts/8b3db2c1-03e0-4736-aa74-c3f7547a8dd3
Content-Type: application/json
Accept: application/json
# Authorization: Bearer <your-jwt-token-if-needed>

{
  "employeeId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "startTime": "2024-11-26T10:00:00",
  "endTime": "2024-11-26T18:00:00",
  "shiftType": "Normal",
  "status": "Confirmed",
  "clockInTime": "2024-11-26T9:00:00",
  "clockOutTime": "2024-11-26T18:00:00",
  "shiftHours": 8.0
}

### Delete a Shift by ID
DELETE http://localhost:5001/shifts/8b3db2c1-03e0-4736-aa74-c3f7547a8dd3
# Authorization: Bearer <your-jwt-token-if-needed>
