# Get All Shifts
GET http://localhost:3007/shifts
Accept: application/json
#Authorization: Bearer <your-jwt-token-if-needed>

### Get Shifts by Employee ID
GET http://localhost:3007/shifts?employeeId=71c0da1e-f97d-412c-a951-41950a20f2fc
Accept: application/json
#Authorization: Bearer <your-jwt-token-if-needed>

###get total hours by employee
GET http://localhost:5001/shifts/71c0da1e-f97d-412c-a951-41950a20f2fc/hours

GET http://localhost:3007/shifts/71c0da1e-f97d-412c-a951-41950a20f2fc/hours
Accept: application/json

### Get Shift by ID
GET http://localhost:5001/shifts/6aa95d50-eea3-4364-8e0e-c0a09f287b9b
GET http://localhost:3007/shifts/60477830-9bae-458b-b8ab-da64f3b86583
Accept: application/json
# Authorization: Bearer <your-jwt-token-if-needed>

### Create a new Shift
POST http://localhost:3007/shifts
Content-Type: application/json
Accept: application/json
# Authorization: Bearer <your-jwt-token-if-needed>

{
  "employeeId": "2dc142cb-c95d-4ab5-a258-1d04c2d6c244",
  "startTime": "2025-12-26T09:00:00",
  "endTime": "2025-12-26T17:00:00",
  "shiftType": "Standby"
}

### Update a Shift by ID
PUT http://localhost:3007/shifts/290822dd-b5f6-46fe-9682-d3d010ed0d8f
Content-Type: application/json
Accept: application/json

{
    "startTime": "2024-12-24T10:00:00",
    "endTime": "2024-12-25T18:00:00",
    "shiftType": "Normal", 
    "status": "Confirmed",
    "clockInTime": "2024-12-24T10:15:00",
    "clockOutTime": null
}
    

### Delete a Shift by ID
DELETE http://localhost:5001/shifts/6aa95d50-eea3-4364-8e0e-c0a09f287b9b
DELETE http://localhost:3007/shifts/60477830-9bae-458b-b8ab-da64f3b86583
# Authorization: Bearer <your-jwt-token-if-needed>

### DOESNT WORK Delete a Shifts by Employee ID - needs to be discussed
DELETE http://localhost:3007/shifts/delete/e2923af0-b60b-4c34-8e5d-cf1f06f3e1f0
# Authorization: Bearer <your-jwt-token-if-needed>
