name: Deploy to OpenShift on Change

on:
  push:
    branches:
      - feature/git-actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Fetch the latest 2 commits to ensure 'before' commit is available

      - name: Install OpenShift CLI (oc)
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar -xzf oc.tar.gz
          sudo mv oc /usr/local/bin/oc
          oc version --client

      - name: Log in to OpenShift
        run: |
          oc login ${{ secrets.OPENSHIFT_SERVER }} --token=${{ secrets.OPENSHIFT_TOKEN }} --insecure-skip-tls-verify=true

      - name: Detect Changes
        id: changes
        run: |
          # Check for changes in api-gateway and event-service directories
          echo "Checking for changed files..."
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "Changed files: $CHANGED_FILES"

          if echo "$CHANGED_FILES" | grep -q '^api-gateway/'; then
            echo "api_gateway=true" >> $GITHUB_ENV
          fi
          
      - name: Deploy API Gateway
        if: env.api_gateway == 'true'
        run: |
          echo "Deploying API Gateway..."
          oc project ${{ secrets.NAMESPACE }}
          oc apply -f api-gateway/deployment.yaml